language: dart
sudo: false

# Only run one instance of the formatter and the analyzer, rather than running
# them against each Dart version.
matrix:
  include:
  - dart: dev
    dart_task: dartfmt
  - dart: dev
    env: PROTOC_VERSION=3.0.0
    install: ./tool/travis/setup.sh
    script: ./tool/travis/test.sh
  - dart: dev
    env: PROTOC_VERSION=3.3.0
    install: ./tool/travis/setup.sh
    script: ./tool/travis/analyze.sh
  - dart: dev
    env: PROTOC_VERSION=3.3.0
    install: ./tool/travis/setup.sh
    script: ./tool/travis/test.sh

branches:
  only: [master]

cache:
  directories:
  - $HOME/.pub-cache
