name: protoc_plugin
version: 0.7.9
author: Dart Team <misc@dartlang.org>
description: Protoc compiler plugin to generate Dart code
homepage: https://github.com/dart-lang/dart-protoc-plugin
environment:
  sdk: '>=1.21.0 <2.0.0'
dependencies:
  fixnum: ^0.10.5
  path: ^1.0.0
  protobuf: ^0.7.0
  dart_style: ^1.0.6
dev_dependencies:
  browser: any
  test: ^0.12.0
executables:
  protoc-gen-dart: protoc_plugin
