name: protoc-plugin
version: 0.3.0
authors:
- Dart Team <misc@dartlang.org>
description: Protoc compile to generate Dart code
homepage: https://github.com/dart-lang/protoc-plugin
environment:
  sdk: '>=0.8.7'
dependencies:
  protobuf: '>=0.3.0'
dev_dependencies:
  unittest: any
